# Generated by Django 3.1.2 on 2020-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='name',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
